name: Dry-run Renovate

on:
  workflow_dispatch:

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
      - uses: actions/checkout@v3

      - uses: cybozu/renovate-dry-run-action@v1
        with:
          config-file: renovate.json5
