name: Dry-run Renovate

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/dry-renovate.yaml
      - renovate.json5

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cybozu/renovate-dry-run-action@v1
        with:
          config-file: renovate.json5
